mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:question_id>/', views.details, name='details'),
    path('<int:pk>/', views.DetailsView.as_view(), name='details'),
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    text = models.CharField(max_length=200)
    date_published = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        # return self.date_published >= timezone.now() - datetime.timedelta(days=1)
        return now - datetime.timedelta(days=1) <= self.date_published <= now

    was_published_recently.admin_order_field = 'date_published'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    vote_count = models.IntegerField(default=0)

    def __str__(self):
        return self.text

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question

def indexOld(request):
    latest_question_list = Question.objects.order_by('-date_published')[:5]
    # template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    # output = ', '.join([q.text for q in latest_question_list])
    # return HttpResponse(output)
    # return HttpResponse(template.render(context, request))
    return render(request, 'polls/index.html', context)

def detailsOld(request, question_id):
    # try:
    #     # Alternatively: id=question_id
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist.")
    # return HttpResponse("You're looking at question %s." % question_id)

    # There’s also a get_list_or_404() function, which works just
    # as get_object_or_404() – except using filter() instead of get().
    # It raises Http404 if the list is empty.
    question = get_object_or_404(Question, id=question_id)
    return render(request, 'polls/details.html', {'question': question})

def resultsOld(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    return render(request, 'polls/results.html', {'question': question})

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions (not including
        those set to be published in the future)."""
        # return Question.objects.order_by('-date_published')[:5]
        return Question.objects.filter(
            date_published__lte=timezone.now()
            ).order_by('-date_published')[:5]

class DetailsView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(date_published__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    choice_id = request.POST['choice']
    try:
        selected_choice = question.choice_set.get(id=choice_id)
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
            })
    else:
        selected_choice.vote_count += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/details.html
<h1>{{ question.text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:details' question.id %}">{{ question.text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.text }} -- {{ choice.vote_count }} vote{{ choice.vote_count|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}">Vote again?</a>